CREATE DATABASE quanlybanhang;

USE quanlybanhang;

CREATE TABLE Customer (
cID INT NOT NULL PRIMARY KEY,
cName VARCHAR(50) NOT NULL,
cAge VARCHAR (10) NOT NULL
);

CREATE TABLE Orders (
oID INT NOT NULL PRIMARY KEY,
cID INT NOT NULL,
oDate DATETIME NOT NULL,
oTotalPrice DOUBLE NOT NULL,
FOREIGN KEY (cID) REFERENCES Customer (cID) 
);

CREATE TABLE Product(
pID INT NOT NULL PRIMARY KEY,
pName VARCHAR(50) NOT NULL,
pPrice DOUBLE NOT NULL
);

CREATE TABLE OrderDetail(
oID INT NOT NULL,
pID INT NOT NULL,
odQTY VARCHAR(20) NOT NULL,
CONSTRAINT pk_orderdetail PRIMARY KEY (oID,pID),
FOREIGN KEY (oID) REFERENCES Orders (oID),
FOREIGN KEY (pID) REFERENCES Product (pID)
);

